Imports System
Imports System.Collections.Generic
Imports System.Linq
Imports System.Text.RegularExpressions
Imports System.Web
Imports System.Web.UI
Imports System.Web.UI.WebControls
Imports Telerik.Web.UI
Imports System.Data
Imports System.Data.SqlClient
Imports System.Configuration
Imports System.Net
Imports eZee.Data

Partial Public Class Controls_alarmview
    Inherits Global.System.Web.UI.UserControl
    Private automationPage As String = "http://whatismyipaddress.com/ip-hostname"
    Public Function getconnection() As ConnectionStringSettings
        Return ConnectionStringSettingsFactory.getconnection()
    End Function

    Private Sub Controls_alarmview_Init(sender As Object, e As System.EventArgs) Handles Me.Init
        'SqlDataSource1.ConnectionString = ConnectionStringSettingsFactory.getconnection().ConnectionString
        'SqlDataSource2.ConnectionString = ConnectionStringSettingsFactory.getconnection().ConnectionString
        'SqlDataSource3.ConnectionString = ConnectionStringSettingsFactory.getconnection().ConnectionString
        'SqlDataSource5.ConnectionString = ConnectionStringSettingsFactory.getconnection().ConnectionString
    End Sub

    'Public Function PivotTable(ByVal [source] As DataTable) As DataTable
    '    Dim dest As New DataTable("Pivoted" + [source].TableName)

    '    dest.Columns.Add(" ")

    '    Dim r As DataRow
    '    For Each r In [source].Rows
    '        dest.Columns.Add(r(0).ToString())
    '    Next r
    '    Dim i As Integer
    '    For i = 0 To ([source].Columns.Count - 1) - 1
    '        dest.Rows.Add(dest.NewRow())
    '    Next i

    '    For i = 0 To dest.Rows.Count - 1
    '        Dim c As Integer
    '        For c = 0 To dest.Columns.Count - 1
    '            If c = 0 Then
    '                dest.Rows(i)(0) = [source].Columns((i + 1)).ColumnName
    '            Else
    '                dest.Rows(i)(c) = [source].Rows((c - 1))((i + 1))
    '            End If
    '        Next c
    '    Next i
    '    dest.AcceptChanges()
    '    Return dest
    'End Function 'PivotTable

    'Public Function GetDataTable(ByVal query As String) As DataTable
    '    Dim ConnString As String = ConfigurationManager.ConnectionStrings("LocalSqlServer").ConnectionString
    '    Dim conn As SqlConnection = New SqlConnection(ConnString)
    '    Dim adapter As SqlDataAdapter = New SqlDataAdapter
    '    adapter.SelectCommand = New SqlCommand(query, conn)
    '    Dim table1 As New DataTable
    '    conn.Open()
    '    Try
    '        adapter.Fill(table1)
    '    Finally
    '        conn.Close()
    '    End Try
    '    Return table1
    'End Function

    'Protected Sub RadGrid1_NeedDataSource(ByVal source As Object, ByVal e As GridNeedDataSourceEventArgs) Handles RadGrid1.NeedDataSource
    '    RadGrid1.DataSource = PivotTable(GetDataTable("SELECT TOP 5 sgm,car_Type, PLAT_No  Country FROM CarInfom"))
    'End Sub

    'Protected Sub RadGrid1_ItemCreated(ByVal sender As Object, ByVal e As GridItemEventArgs) Handles RadGrid1.ItemCreated
    '    If TypeOf e.Item Is GridDataItem Then
    '        CType(e.Item, GridDataItem)(CType(RadGrid1.MasterTableView.AutoGeneratedColumns(0), GridBoundColumn).UniqueName).Font.Bold = True
    '        CType(e.Item, GridDataItem)(CType(RadGrid1.MasterTableView.AutoGeneratedColumns(0), GridBoundColumn).UniqueName).BackColor = System.Drawing.SystemColors.Control
    '        CType(e.Item, GridDataItem)(CType(RadGrid1.MasterTableView.AutoGeneratedColumns(0), GridBoundColumn).UniqueName).BorderColor = System.Drawing.Color.White
    '    End If
    'End Sub


    Private Sub Controls_alarmview_Load(sender As Object, e As System.EventArgs) Handles Me.Load
        'multi tanat
        
        '
        Label1.Text = HttpContext.Current.User.Identity.Name
        Label2.Text = Dns.GetHostName()
        Dim ipmosso As IPHostEntry
        ipmosso = Dns.GetHostEntry(Dns.GetHostName)
        Label3.Text = ipmosso.AddressList(0).ToString()
        Dim ipaddress As String
        ipaddress = Request.ServerVariables("HTTP_X_FORWARDED_FOR")
        If ipaddress = "" Or ipaddress Is Nothing Then
            ipaddress = Request.ServerVariables("REMOTE_ADDR")
        End If

        Label3.Text = Label3.Text & "  ::  " & ipaddress

        ' Dim myIp As String = GetExternalIP(automationPage)
        ' Label4.Text = myIp
    End Sub


    Function GetExternalIP(ByVal webPath As String) As String
        Dim output As String = ""
        Dim webReq As New System.Net.WebClient
        output = System.Text.Encoding.ASCII.GetString((webReq.DownloadData(webPath)))
        webReq.Dispose()
        Return output
    End Function


End Class
